(#5, #8) Move core extension to new extensions repository
chocolatey-community/chocolatey-extensions pull request #9
Opened 2022-03-21 09:31 UTC by AdmiringWorm

This pull request adds the `chocolatey-core.extension` to this repository, and updates the URLs to be pointing to the correct location here.

Additionally the aliases that was used in `chocolatey-core.extension` have been expanded to ensure that we don't get alias related bugs anymore.

related to #5 and fixes #8

2022-03-21 18:05 UTC, vexx32 approved these changes
Looks good to me, thanks for taking care for this!

2022-03-21 18:11 UTC, vexx32 requested changes
Almost missed these, there's a couple more aliases we can clean up in the psm1 here.

2022-03-21 18:11 UTC, vexx32 commented on src/chocolatey-core.extension/extensions/chocolatey-core.psm1
> +$funcs | ? { $_ -cmatch '^[A-Z]+'} | % { Export-ModuleMember -Function $_ }
```suggestion
$pre = Get-ChildItem Function:\*
Get-ChildItem "$ScriptRoot\*.ps1" |
    Where-Object { $_.Name -cmatch '^[A-Z]+' } |
    ForEach-Object { . $_  }
$post = Get-ChildItem Function:\*
$funcs = Compare-Object $pre $post |
    Select-Object -ExpandProperty InputObject |
    Select-Object -ExpandProperty Name
$funcs |
    Where-Object { $_ -cmatch '^[A-Z]+'} |
    ForEach-Object { Export-ModuleMember -Function $_ }
```

2022-03-22 09:23 UTC, gep13 commented on src/chocolatey-core.extension/extensions/chocolatey-core.psm1
> +$funcs | ? { $_ -cmatch '^[A-Z]+'} | % { Export-ModuleMember -Function $_ }
@AdmiringWorm what are your thoughts here?  If you are happy, I can commit this suggestion, and get this PR updated, ready for merging.

2022-03-22 09:26 UTC, gep13 requested changes

2022-03-22 09:26 UTC, gep13 commented on src/chocolatey-core.extension/chocolatey-core.extension.nuspec
> +    <docsUrl>https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/README.md</docsUrl>
Is there a reason that this is still pointed to old repository?

2022-04-07 09:17 UTC, AdmiringWorm commented on src/chocolatey-core.extension/extensions/chocolatey-core.psm1
> +$funcs | ? { $_ -cmatch '^[A-Z]+'} | % { Export-ModuleMember -Function $_ }
hmm, TBH the exclusion never actually work, as the aliases and functions aren't made visible when this module is loaded.

All Chocolatey CLI helpers aren't visible until the whole module has loaded completely.

However, wouldn't hurt to add this as well, but should eventually be changed to something similar to what is in the compatibility package instead.

https://github.com/chocolatey-community/chocolatey-extensions/blob/37760cac836dc80397f44239852aba2b64d0e0a1/src/chocolatey-compatibility.extension/extensions/chocolatey-compatibility.psm1

2022-04-07 09:18 UTC, AdmiringWorm commented on src/chocolatey-core.extension/chocolatey-core.extension.nuspec
> +    <docsUrl>https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/README.md</docsUrl>
Just missed it, I'll get it changed.

2022-04-07 09:55 UTC, AdmiringWorm commented on src/chocolatey-core.extension/extensions/chocolatey-core.psm1
> +$funcs | ? { $_ -cmatch '^[A-Z]+'} | % { Export-ModuleMember -Function $_ }
I have included this change.

2022-04-07 09:56 UTC, AdmiringWorm commented on src/chocolatey-core.extension/chocolatey-core.extension.nuspec
> +    <docsUrl>https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/README.md</docsUrl>
I have fixed this URL now, as well as another URL I noticed was wrong.

2022-04-07 12:43 UTC, vexx32 approved these changes
Looks good to me, thanks for sorting that out! One minor question but other than that, this looks great!

2022-04-07 12:43 UTC, vexx32 commented on src/chocolatey-core.extension/extensions/Get-AppInstallLocation.ps1
> +﻿. "$PSScriptRoot\Get-UninstallRegistryKey.ps1"
This shouldn't be needed since all the functions get imported by the psm1, right?

2022-04-07 13:20 UTC, AdmiringWorm commented on src/chocolatey-core.extension/extensions/Get-AppInstallLocation.ps1
> +﻿. "$PSScriptRoot\Get-UninstallRegistryKey.ps1"
hmm, I thought I had removed that one. It was there for legacy purposes, due to it needing to be sourced when it was in the `chocolatey-packages` repository. I'll get it removed

2022-04-08 12:57 UTC, merged

2022-04-08 12:57 UTC, vexx32 commented
Thanks for adding this @AdmiringWorm! 💖